In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [28]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.03125


In [29]:
import numpy as np
from time import process_time

# Create array directly with np.arange instead of list comprehension
# Use a more reasonable size (e.g., 10 million elements)
np_array = np.arange(10000000)  # Much more memory efficient

start_time = process_time()

np_array += 5    # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.015625


In [30]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.015625


# NumPy Arrays

In [31]:
# initiating a list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [32]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [34]:
# creating a 1 D array
a = np.array([1,2,3,4])
print(a)

a.shape

[1 2 3 4]


(4,)

In [37]:
# 2D/3D array
b = np.array([(1,2,3,4),(5,6,7,8), (1,2,3,4)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


(3, 4)

In [39]:
#specifying the datatype
b = np.array([(1,2,3,4),(5,6,7,8), (1,2,3,4)], dtype=float)
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]]


In [40]:
# Initial Placeholders in numpy arrays
# creating a numpy array of Zeros

x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
# numpy array with all values as 1s

y = np.ones((3,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [44]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
# create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.92487566 0.57429158 0.76803867 0.32735146]
 [0.40131003 0.86688167 0.81670662 0.91084834]
 [0.82860988 0.91887029 0.0776811  0.9511337 ]]


In [52]:
# create a numpy array with random values (integers) within a specific range

c = np.random.randint(10,200,(3,5))
print(c)

[[183 124 126 194 186]
 [ 41  12  77  28  54]
 [125  61  83 120  45]]


In [55]:
# array of evenly spaced values  --> specifying no of values required
e = np.linspace(10, 30, 5)
print(e)

[10. 15. 20. 25. 30.]


In [57]:
# array of evenly spaced values  --> specifying the step
d = np.arange(10, 30, 4)
print(d)

[10 14 18 22 26]


In [59]:
# covert list to numpy array
list2 = [10,20,30,40,50]
print

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

## Analysing a numpy array

In [60]:
c = np.random.randint(10,90,(5,5))
print(c)

[[32 88 73 45 45]
 [34 45 85 77 17]
 [34 71 57 88 78]
 [43 77 67 36 34]
 [30 12 48 43 52]]


In [61]:
# array dimension
print(c.shape)

(5, 5)


In [62]:
# no of dimensions
print(c.ndim)

2


In [63]:
# no of elements present in an array
print(c.size)

25


In [65]:
# checking data type of the values in the array
print(c.dtype)

int32


## Mathematical operations on a np array

In [66]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)   #joins/concatenete two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [67]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[1 5 7]
 [3 4 7]
 [6 7 2]]
[[16 18 14]
 [11 14 13]
 [13 14 19]]


In [70]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[[17 23 21]
 [14 18 20]
 [19 21 21]]
[[16 90 98]
 [33 56 91]
 [78 98 38]]
[[-15 -13  -7]
 [ -8 -10  -6]
 [ -7  -7 -17]]
[[0.0625     0.27777778 0.5       ]
 [0.27272727 0.28571429 0.53846154]
 [0.46153846 0.5        0.10526316]]


### array manipulation

In [74]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 4 7]
 [0 1 3]]
(2, 3)


In [75]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 0]
 [4 1]
 [7 3]]
(3, 2)


In [76]:
#transpose 2
array2 = np.random.randint(0,10,(2,3))
print(array2)
print(array2.shape)

[[1 6 2]
 [4 3 6]]
(2, 3)


In [77]:
trans2 = array2.T
print(trans2)
print(trans2.shape)

[[1 4]
 [6 3]
 [2 6]]
(3, 2)


### Reshaping aray

In [79]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 1 9]
 [5 3 1]]
(2, 3)


In [80]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 1]
 [9 5]
 [3 1]]
(3, 2)
