In [5]:
import numpy as np

arr1 = np.array([1,2,3,9])

print(arr1)

[1 2 3 9]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
print(arr1.shape)

(4,)


In [8]:
arr1[3] = 7
print(arr1)

[1 2 3 7]


In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [10]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
arr2[1][0]

np.int64(4)

In [13]:
arr2[1][0] =  8
print(arr2)

[[1 2 3]
 [8 5 6]]


In [14]:
arr2.shape

(2, 3)